user:
    resource: "@UserBundle/Resources/config/routing.yml"


post:
    resource: "@AppBundle/Controller/postController.php"
    type: annotation


comentarios:
    resource: "@AppBundle/Controller/ComentariosController.php"
    type: annotation
    prefix: /Comment

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media



games:
    resource: "@AppBundle/Controller/gameController.php"
    type: annotation
    prefix: /Games




