user:
    resource: "@UserBundle/Resources/config/routing.yml"


post:
    resource: "@AppBundle/Controller/postController.php"
    type: annotation


comentarios:
    resource: "@AppBundle/Controller/ComentariosController.php"
    type: annotation
    prefix: /Comment

games:
    resource: "@AppBundle/Controller/gameController.php"
    type: annotation
    prefix: /Games




