services:
    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }
    admin.category:
            class: AppBundle\Admin\categoryAdmin
            arguments: [~, AppBundle\Entity\Category, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Category }
    admin.post:
            class: AppBundle\Admin\postAdmin
            arguments: [~, AppBundle\Entity\Post, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Post }

    app.form.profile:
            class: Trascastro\UserBundle\Form\editProfileType
            tags:
                - { name: form.type, alias: user_bundleedit_profile_type  }






